###### 自动求导，计算反向传播

In [10]:
import torch

In [11]:
x = torch.rand(3,4,requires_grad=True)
x

tensor([[0.9401, 0.2502, 0.0783, 0.2259],
        [0.0658, 0.7672, 0.0127, 0.7515],
        [0.5508, 0.7457, 0.4985, 0.2340]], requires_grad=True)

In [12]:
b = torch.rand(3,4,requires_grad=True)
b

tensor([[0.2167, 0.2414, 0.1994, 0.6241],
        [0.9907, 0.5396, 0.6430, 0.5096],
        [0.7964, 0.3973, 0.4197, 0.8406]], requires_grad=True)

In [13]:
t=x+b
y = t.sum()
y.backward()
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
x.requires_grad,b.requires_grad,t.requires_grad

(True, True, True)